networks:
  default:

services:

  database:
    container_name: database
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_USER: $DB_USERNAME
    ports:
      - 127.0.0.1:$DB_LOCAL_PORT:$DB_PORT
    volumes:
      - database-vlm:/var/lib/mysql:rw
      - ./database:/docker-entrypoint-initdb.d/
    networks:
      - default

  app:
    container_name: app
    depends_on:
      - database
    build: ./app
    restart: unless-stopped
    env_file:
      - ./.env
    expose:
      - $APP_PORT
    ports:
      - $APP_LOCAL_PORT:$APP_PORT
    environment:
      - DB_HOST=$DB_HOST
      - DB_USERNAME=$DB_USERNAME
      - DB_PORT=$DB_PORT
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
    volumes:
      - ./app:/app
      - /app/node_modules
    networks:
      - default

volumes:
  database-vlm:
